name: Deploy Next.js Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build


    - name: Run Lighthouse CI
      run: npx -y @lhci/cli autorun

    - name: Run aXe accessibility tests
      run: |
        npm start &
        SERVER_PID=$!
        npx wait-on http://localhost:3000
        npx -y @axe-core/cli http://localhost:3000 --exit
        kill $SERVER_PID

    - name: Lint
      run: npm run lint
      
    # Additional deployment steps would go here
    # For example, deploying to Vercel, Netlify, or custom hosting 